import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import Header from "@/components/Header";

const roboto = Roboto({ 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "700", "900"] 
});

export const metadata: Metadata = {
  title: "Purwadhika Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
